name: fatiando-data-lightning-creek-magnetic-grid
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.9.*
  - pip
  - numpy
  - pandas
  - jupyterlab
  - matplotlib
  - xarray
  - netcdf4
  - pyproj
  - pykdtree
  # PyGMT for plotting
  - gmt==6.3.*
  - pygmt==0.6.*
  # Fatiando
  - pooch==1.6.*
  - harmonica==0.5.*
  - verde==1.7.*
